### ISSUE TITLE
Users should be able to map TODO types to GitHub Labels

### ISSUE THREAD

**Issue by codeimpossible** [troublecatstudios/todo-issues#7]
It would be useful to allow users to map the TODO types to labels within the action config:

```yaml
- uses: troublecatstudios/todo-issues@v1
  with:
    markers: |
      TODO: enhancement
      BUG: bug
      QUESTION: question
      FIXME: bug
      OPTIMIZE
      HELP: enhancement, help wanted
```

I'm thinking there could be many labels per marker, comma separated and trimmed before we use them.

### Unknowns: 
- Are labels case sensitive in the GitHub API?
