### ISSUE TITLE
Users should be able to add pretty much anything as a marker

### ISSUE THREAD

**Issue by codeimpossible** [troublecatstudios/todo-issues#8]
I imagine users would have their own conventions that might not fit in the default set of `TODO, HACK, FIXME, BUG, OPTIMIZE` that this looks for by default. They should be able to override the markers within the action settings:

```yaml
- uses: troublecatstudios/todo-issues@v1
  with:
    markers: |
      TODO
      QUESTION
      BUG
```

This config would only search for `TODO`, `QUESTION` and `BUG` markers within comments.

### Unknowns
- What happens if they change this after having a bunch of issues open with the other marker types?
